export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const SELECTING_AVATAR = 'SELECTING_AVATAR'

export const OPTION_1 = 'OPTION_1'
export const OPTION_2 = 'OPTION_2'
export const OPTION_3 = 'OPTION_3'